// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANQLaxgWNqSfsdJUklM4qt104evQK_5j0',
    appId: '1:901946726100:web:e707ba2ee7dc9a99c04d41',
    messagingSenderId: '901946726100',
    projectId: 'katalks-7e05c',
    authDomain: 'katalks-7e05c.firebaseapp.com',
    storageBucket: 'katalks-7e05c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVikXm7A6O3GFJJRNmkSJv_O6pMqqq7pA',
    appId: '1:901946726100:android:9be0826f121ac616c04d41',
    messagingSenderId: '901946726100',
    projectId: 'katalks-7e05c',
    storageBucket: 'katalks-7e05c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBj_x_s91zYAJU-6W09RrGC_rnqmg00HU',
    appId: '1:901946726100:ios:5fe5a0fbb763cf5ac04d41',
    messagingSenderId: '901946726100',
    projectId: 'katalks-7e05c',
    storageBucket: 'katalks-7e05c.appspot.com',
    iosBundleId: 'com.example.katalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBj_x_s91zYAJU-6W09RrGC_rnqmg00HU',
    appId: '1:901946726100:ios:ad97da2317ab19e0c04d41',
    messagingSenderId: '901946726100',
    projectId: 'katalks-7e05c',
    storageBucket: 'katalks-7e05c.appspot.com',
    iosBundleId: 'com.example.katalk.RunnerTests',
  );
}
